version: '3.6'

services:

 lasallercamison.mdas:
    image: lasallercamison.mdas
    container_name: helloworld
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3080:80" 
      - "3443:443"
    networks:
      - helloworld  

networks:
    helloworld:
        driver: bridge